### ISSUE TITLE
raspberry pi glibc (solved)

### ISSUE THREAD

**Issue by TheRealKushal** [powenn/AltServer-Linux-PyScript#6] opened 2023-07-08 16:35 UTC
not able to install altstore using the tethered mode to my iphone or my ipad,I keep trying so many times but it won't install the altstore onto my phone.

**Comment by supermatttt** [comment] 2023-07-08 23:26
`Do you want to install AltStore ? (y/n) [n for select your own iPA] : y
Installing app...
parse anisette data ret
Alert: Could not install AltStore.ipa to unknown.
    Failed to connect to any resolved endpoint
Press any key to continue...

Exception: Failed to connect to any resolved endpoint
 0# 0x00184FF0

Finished!
Enter OPTION to continue : e
Terminated

anisette-server: no process found`

**Comment by TheRealKushal** [comment] 2023-07-09 00:39
I get the exact same message when I try this.

**Comment by powenn** [comment] 2023-07-09 00:50
Try reconnect your devices 
Also you can use p option for checking pair status 

If your device can't be detected 
Try pairing it manually before using the script 

idevicepair pair

**Comment by TheRealKushal** [comment] 2023-07-09 01:29
I can see my device is properly paired and I can even enter my Apple ID and password but when I type "y" for AltStore to download it wont work.

**Comment by powenn** [comment] 2023-07-09 01:40
What's your OS  and its arch
All dependencies installed ?
The two service enabled and running ?

**Comment by TheRealKushal** [comment] 2023-07-09 01:59
I'm on raspberyy pi os 64 bit on raspberry pi 4, all dependencies are upto date and both the services are active.

**Comment by powenn** [comment] 2023-07-09 02:04
Run uname -m in terminal 
I need to check something 

Does anisette server exists in the resource dir?

**Comment by supermatttt** [comment] 2023-07-09 02:17
> Run uname -m in terminal I need to check something
> 
> Does anisette server exists in the resource dir?

pi@raspberrypi:~ $ uname -m
armv7l


pi@raspberrypi:~/Downloads/resource $ ls
AltServer  AltStore.ipa  anisette-server  netmuxd

**Comment by powenn** [comment] 2023-07-09 02:20
> `Do you want to install AltStore ? (y/n) [n for select your own iPA] : y
> 
> Installing app...
> 
> parse anisette data ret
> 
> Alert: Could not install AltStore.ipa to unknown.
> 
>     Failed to connect to any resolved endpoint
> 
> Press any key to continue...
> 
> 
> 
> Exception: Failed to connect to any resolved endpoint
> 
>  0# 0x00184FF0
> 
> 
> 
> Finished!
> 
> Enter OPTION to continue : e
> 
> Terminated
> 
> 
> 
> anisette-server: no process found`

Seems anisette server on your host not running correctly 

Check if this cmd runs properly 

anisette-server -n 127.0.0.1 -p 6969

**Comment by supermatttt** [comment] 2023-07-09 02:35
pi@raspberrypi:~/Downloads/resource $ ./anisette-server -n 127.0.0.1 -p 6969
./anisette-server: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette-server)
./anisette-server: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.32' not found (required by ./anisette-server)
./anisette-server: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette-server)



pi@raspberrypi:~/Downloads/resource $ sudo apt-get update
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 https://repo.homebridge.io stable InRelease                                       
Get:3 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]             
Fetched 15.0 kB in 3s (5,772 B/s)                                       
Reading package lists... Done
pi@raspberrypi:~/Downloads/resource $ sudo apt-get install libc6
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libc6 is already the newest version (2.31-13+rpt2+rpi1+deb11u5).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by powenn** [comment] 2023-07-09 02:46
So the problem is anisette server not running

**Comment by powenn** [comment] 2023-07-09 02:48
Check this

https://github.com/Dadoum/Provision/issues/81

**Comment by powenn** [comment] 2023-07-09 02:52
Or you have to upgrade glibc properly

**Comment by TheRealKushal** [comment] 2023-07-09 03:05
> 

pi@kushal:~ $ uname -m
aarch64



and yes in the resource folder there is anisette server that exists

**Comment by powenn** [comment] 2023-07-09 03:07
> > 
> 
> 
> 
> pi@kushal:~ $ uname -m
> 
> aarch64
> 
> 
> 
> 
> 
> 
> 
> and yes in the resource folder there is anisette server that exists
> 
> 
> 
> 

Try 

anisette-server -n 127.0.0.1 -p 6969

**Comment by TheRealKushal** [comment] 2023-07-09 03:08
> ./anisette-server -n 127.0.0.1 -p 6969

pi@kushal:~ $ cd resource
pi@kushal:~/resource $ ls
AltServer  AltStore.ipa  anisette-server  netmuxd
pi@kushal:~/resource $ ./anisette-server -n 127.0.0.1 -p 6969
./anisette-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette-server)
./anisette-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./anisette-server)
./anisette-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette-server)
pi@kushal:~/resource $

**Comment by powenn** [comment] 2023-07-09 03:09
> > ./anisette-server -n 127.0.0.1 -p 6969
> 
> pi@kushal:~ $ cd resource pi@kushal:~/resource $ ls AltServer AltStore.ipa anisette-server netmuxd pi@kushal:~/resource $ ./anisette-server -n 127.0.0.1 -p 6969 ./anisette-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./anisette-server) ./anisette-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./anisette-server) ./anisette-server: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./anisette-server) pi@kushal:~/resource $

Check this
https://github.com/Dadoum/Provision/issues/81

**Comment by TheRealKushal** [comment] 2023-07-09 03:14
when im trying to build anisette server with dub compiler I get the error:

pi@kushal:~/Provision $ dub build -b release
Invalid SemVer format: d494cf3fe79a2bb20583173c0c8cf85ef33b719e

**Comment by powenn** [comment] 2023-07-09 03:16
> when im trying to build anisette server with dub compiler I get the error:
> 
> 
> 
> pi@kushal:~/Provision $ dub build -b release
> 
> Invalid SemVer format: d494cf3fe79a2bb20583173c0c8cf85ef33b719e
> 
> 

Then you should ask in provision issue

**Comment by TheRealKushal** [comment] 2023-07-09 04:15
WOW thank you so much for pointing me in the right direction there were a lot of github issues that I had to read on the way to get it to work due to the very poor documentation for newcomers on the Provision site. If anybody else needs any help trying to get provision to work feel free to reach out to me.

**Comment by powenn** [comment] 2023-07-09 04:17
> WOW thank you so much for pointing me in the right direction there were a lot of github issues that I had to read on the way to get it to work due to the very poor documentation for newcomers on the Provision site. If anybody else needs any help trying to get provision to work feel free to reach out to me.

So did you get it works ?

**Comment by TheRealKushal** [comment] 2023-07-09 04:18
Yes and thanks.

**Comment by supermatttt** [comment] 2023-07-09 12:01
> Yes and thanks.

@TheRealKushal
Can you help me with the semver error? I tried cmake and/or dub, can’t get either to work right. 

Sorry to clutter up your thread @powenn

**Comment by powenn** [comment] 2023-07-09 12:26
> > Yes and thanks.
> 
> 
> 
> Can you help me with the semver error? I tried cmake and/or dub, can’t get either to work right. 
> 
> 
> 
> Sorry to clutter up your thread @powenn

I think @TheRealKushal would be the better one for helping you solve this problem because he already solved it one time 

But sure, I will try helping you solve it

**Comment by powenn** [comment] 2023-07-09 12:29
@supermatttt  try
dub build -b release :anisette-server

**Comment by supermatttt** [comment] 2023-07-09 12:52
> try
> dub build -b release :anisette-server
@powenn 
Thank you so much for taking the time out to help solve this issue. Unfortunately it gave the same error. I’m hoping Kush will chime back in !!

Invalid SemVer format: d494cf3fe79a2bb20583173c0c8cf85ef33b719e

**Comment by powenn** [comment] 2023-07-09 13:10
> > try
> > dub build -b release :anisette-server
> > @powenn
> > Thank you so much for taking the time out to help solve this issue. Unfortunately it gave the same error. I’m hoping Kush will chime back in !!
> 
> Invalid SemVer format: d494cf3fe79a2bb20583173c0c8cf85ef33b719e

How did you clone the GitHub project

**Comment by powenn** [comment] 2023-07-09 13:12
@supermatttt Did you installed D SDK and compiler ?

**Comment by powenn** [comment] 2023-07-09 13:14
@supermatttt I have an idea

https://github.com/Dadoum/Provision/actions/runs/5437674757
Get the build from action and test it

**Comment by powenn** [comment] 2023-07-09 13:16
> > try
> > dub build -b release :anisette-server
> > @powenn
> > Thank you so much for taking the time out to help solve this issue. Unfortunately it gave the same error. I’m hoping Kush will chime back in !!
> 
> Invalid SemVer format: d494cf3fe79a2bb20583173c0c8cf85ef33b719e

I have no idea on it...

**Comment by TheRealKushal** [comment] 2023-07-09 15:37
ok so @supermatttt here is the solution: 

that issue is caused by the lack of dependencies
first download all of the dependencies
0) sudo apt update
1) sudo apt install gdc 
2) sudo apt install dub

now we also get the ldc compiler for that: 
to install ldc : curl -fsS https://dlang.org/install.sh | bash -s ldc

the last dependency is libplist the directions to install are very simple for this one so I will just link the dependency
link: https://github.com/libimobiledevice/libplist

now that you have all of the dependencies we can start building the anisette server with dub.


everytime you run the "dub" command this ldc compiler needs to be working and you have to do it first by activating the compiler and then running the dub command for build. 
so in order to activate the compiler you need to do:  source ~/dlang/ldc-1.32.2/activate

after typing this command you can follow the commands listed on the Provision page
but after doing "dub build -b release" which is the last command on the readme, you also have to type in another command but for some reason the readme on provision does not specify this. you have to also type in: dub build -b release :anisette-server

and now the build for the anisette server should be complete. to use it go to your provision folder and it will be an executable in /bin named "provision_anisette-server"

and then run: ./provision_anisette-server
 
and now open a new terminal and go back to where you have the altserver pyscript and just run: python3 main.py

so in the end you should have two terminals running one is the anisette server and the other is the altserver. I was losing sleep over this because I hate ads on youtube and spotify but finally I got it working. I hope this works. for people that are new to this like me the Provision repository has very limited instructions.

**Comment by Macleykun** [comment] 2023-07-10 16:39
think we can close this issue aswell :^)

**Comment by powenn** [comment] 2023-07-11 01:04
> think we can close this issue aswell :^)

I keep this open because so much people won't check closed issues before asking,so I have to answer the same question so much times

**Comment by supermatttt** [comment] 2023-07-11 15:45
@TheRealKushal
`now we also get the ldc compiler for that:
to install ldc : curl -fsS https://dlang.org/install.sh | bash -s ldc`
Unsupported Arch armv7l

**Closed as completed** 2023-07-14 11:43 UTC
